export const COURSE_OPTIONS = [
    "M.A. (Applied Economics - 5 Years)",
    "M.A. (Economics)",
    "M.A. (English)",
    "M.A. (Hindi)",
    "M.A. (Mass Communication)",
    "M.A. (Public Administration)",
    "M.A. (Telugu Studies)",
    "M.A. (Telugu Studies - Comparative Literature)",
    "M.A. (Urdu)",
    "M.A. (History)",
    "M.A. (Political Science)",
    "M.Com. (e-Commerce)",
    "M.Com. (General)",
    "M.S.W",
    "M.Sc. (Applied Statistics)",
    "M.Sc. (Bio-Technology)",
    "M.Sc. (Botany)",
    "M.Sc. (Chemistry - 2 Years Course in specialization with Organic Chemistry)",
    "M.Sc. (Chemistry - 2 Years with specialization in Pharmaceutical Chemistry)",
    "M.Sc. (Chemistry - 5 Years Integrated with specialization in Pharmaceutical Chemistry)",
    "M.Sc. (Computer Science)",
    "M.Sc. (Food Science & Technology)",
    "M.Sc. (Geo Informatics)",
    "M.Sc. (Mathematics)",
    "M.Sc. (Nutrition & Dietetics)",
    "M.Sc. (Physics)",
    "M.Sc. (Physics - 2 Years with specialization in Electronics)",
    "M.Sc. (Statistics)",
    "M.Sc. (Zoology)",
    "IMBA (Integrated Master of Business Management) (5 Yrs Integrated)",
    "M.B.A",
    "M.C.A",
    "LL.B (3 Years)",
    "LL.M (2 Years)",
    "B.Lib.Sc",
    "B.Ed.",
    "M.Ed.",
    "B.P.Ed.",
  ];
  